// Données mockées pour démonstration
import type { Parcelle, Paiement, User } from "./types"

// Coordonnées de Yaoundé: ~3.8667° N, 11.5167° E
export const mockParcelles: Parcelle[] = [
  {
    id: "1",
    numero: "YDE-001-2024",
    superficie: 500,
    adresse: "ACACIA",
    quartier: "Bastos",
    arrondissement: "Yaoundé 1",
    coordinates: [3.8767, 11.5267],
    proprietaireId: "user1",
    proprietaireNom: "Jean Mbarga",
    proprietaireEmail: "jean.mbarga@email.cm",
    proprietaireTelephone: "+237 6 XX XX XX XX",
    valeurFiscale: 50000000,
    impotAnnuel: 500000,
    statut: "a_jour",
    dernierPaiement: "2024-01-15",
    prochainePaiement: "2025-01-15",
    anneesImpayees: 0,
    montantDu: 0,
  },
  {
    id: "2",
    numero: "YDE-002-2024",
    superficie: 750,
    adresse: "Rond point Express",
    quartier: "Biyem-assi",
    arrondissement: "Yaoundé 2",
    coordinates: [3.8667, 11.5167],
    proprietaireId: "user2",
    proprietaireNom: "Marie Ngo Biyong",
    proprietaireEmail: "marie.ngo@email.cm",
    proprietaireTelephone: "+237 6 XX XX XX XX",
    valeurFiscale: 75000000,
    impotAnnuel: 750000,
    statut: "en_retard",
    dernierPaiement: "2023-01-10",
    prochainePaiement: "2024-01-10",
    anneesImpayees: 1,
    montantDu: 750000,
  },
  {
    id: "3",
    numero: "YDE-003-2024",
    superficie: 1000,
    adresse: "Marché ACACIA",
    quartier: "Biyem-assi",
    arrondissement: "Yaoundé 1",
    coordinates: [3.8867, 11.5367],
    proprietaireId: "user3",
    proprietaireNom: "Paul Etoa",
    proprietaireEmail: "paul.etoa@email.cm",
    proprietaireTelephone: "+237 6 XX XX XX XX",
    valeurFiscale: 100000000,
    impotAnnuel: 1000000,
    statut: "impaye",
    prochainePaiement: "2022-01-15",
    anneesImpayees: 3,
    montantDu: 3000000,
  },
  {
    id: "4",
    numero: "YDE-004-2024",
    superficie: 600,
    adresse: "Ecole publique",
    quartier: "Biyem-assi",
    arrondissement: "Yaoundé 3",
    coordinates: [3.8567, 11.5067],
    proprietaireId: "user1",
    proprietaireNom: "Jean Mbarga",
    proprietaireEmail: "jean.mbarga@email.cm",
    proprietaireTelephone: "+237 6 XX XX XX XX",
    valeurFiscale: 60000000,
    impotAnnuel: 600000,
    statut: "a_jour",
    dernierPaiement: "2024-02-20",
    prochainePaiement: "2025-02-20",
    anneesImpayees: 0,
    montantDu: 0,
  },
  {
    id: "5",
    numero: "YDE-005-2024",
    superficie: 450,
    adresse: "Carrefour biyem-assi",
    quartier: "Biyem-assi",
    arrondissement: "Yaoundé 4",
    coordinates: [3.8467, 11.5467],
    proprietaireId: "user4",
    proprietaireNom: "Françoise Atangana",
    proprietaireEmail: "francoise.atangana@email.cm",
    proprietaireTelephone: "+237 6 XX XX XX XX",
    valeurFiscale: 45000000,
    impotAnnuel: 450000,
    statut: "a_jour",
    dernierPaiement: "2024-03-10",
    prochainePaiement: "2025-03-10",
    anneesImpayees: 0,
    montantDu: 0,
  },
]

export const mockPaiements: Paiement[] = [
  {
    id: "p1",
    parcelleId: "1",
    montant: 500000,
    date: "2024-01-15",
    methode: "carte",
    statut: "complete",
    reference: "PAY-2024-001",
  },
  {
    id: "p2",
    parcelleId: "4",
    montant: 600000,
    date: "2024-02-20",
    methode: "mobile_money",
    statut: "complete",
    reference: "PAY-2024-002",
  },
]

export const mockUsers: User[] = [
  {
    id: "user1",
    nom: "Mbarga",
    prenom: "Jean",
    email: "jean.mbarga@email.cm",
    telephone: "+237 6 XX XX XX XX",
    role: "usager",
    parcelles: ["1", "4"],
  },
  {
    id: "usager",
    nom: "FOKOU",
    prenom: "ALEX",
    email: "fokoualex@gmail.com",
    telephone: "+237 6 XX XX XX XX",
    role: "usager",
    parcelles: [],
  },
    {
    id: "admin1",
    nom: "ELLA",
    prenom: "SYLVAIN",
    email: "ellasylvain@gmail.com",
    telephone: "+237 6 XX XX XX XX",
    role: "usager",
    parcelles: [],
  },
    {
    id: "admin1",
    nom: "ADMIN",
    prenom: "",
    email: "adminfiscfoncier@gmail.com",
    telephone: "+237 6 XX XX XX XX",
    role: "admin",
    parcelles: [],
  },
]
